symbols:
  ORDIUSDT:
    enabled: false
    trend_timeframe: 1d
    signal_timeframe: 4h
    order_amount: 100.0
    max_loss_amount: 20.0
    paused_by_loss: false
  VIRYUALUSDT:
    enabled: true
    trend_timeframe: 4h
    signal_timeframe: 15m
    order_amount: 100.0
    max_loss_amount: 20.0
    paused_by_loss: false
symbol_files:
